# GET http://localhost:3000/users

//###

//GET http://localhost:7000/users/2

//###

POST http://localhost:3000/admin/cars
content-type: application/json

{
    "brand": "Mercedes",
    "model": "cla",
    "type": "sedan",
    "year": "2016",
    "price": "25000",
    "engine": "2.0L inline-4",
    "transmission": "manual",
    "color": "brown",
    "mpg": "27",
    "pictureUrl": "https://blogmedia.dealerfire.com/wp-content/uploads/sites/634/2019/01/Color-Options-for-the-2019-Mercedes-Benz-CLA-Coupe-b8_o.jpg"
}
###

PATCH http://localhost:3000/admin/cars
content-type: application/json

{
    "brand": "Mercedes",
    "model": "a220",
    "type": "sedan",
    "year": "2020",
    "price": "29000",
    "engine": "3.0L inline-4 turbo",
    "transmission": "automatic",
    "color": "white",
    "mpg": "25",
    "pictureUrl": "https://s.aolcdn.com/commerce/autodata/images/USC90MBCCC1A021001.jpg"
}

###

//DELETE http://localhost:7000/users/2
DELETE http://localhost:3000/clear HTTP/1.1

###
POST http://localhost:5000/auth/signin 
content-type: application/json

{

    "password": "ssaammyy"
  }

    "name": {"sam"},
    "email":{"sam@gmail.com"},
    "password":{"sami"}
}

###

POST http://localhost:3000/users/add HTTP/1.1
content-type: application/json

{
    "firstName": "marie",
    "lastName": "curie",
    "email": "marie@gmail.com",
    "password": "mmaarriiee",
    "role": "client",
    "address": "54th ST"
}
 

   
###
GET http://localhost:5000/users

###
GET http://localhost:5000/admin/


###
GET http://localhost:5000/admin/60723bf80ecac8bd463ffce5



###
POST http://localhost:5000/signin  HTTP/1.1
content-type: application/json

{ "_id": 3, "name": "Keith" } 
###

###
DELETE http://localhost:5000/admin/:60723acc0ecac8bd463ffce4           HTTP/1.1
