DELETE http://localhost:3000/clear HTTP/1.1

###
POST http://localhost:5000/auth/signin 
content-type: application/json

{

    "password": "ssaammyy"
  }
 

   
###
GET http://localhost:5000/users

###
GET http://localhost:5000/admin/


###
GET http://localhost:5000/admin/60723bf80ecac8bd463ffce5



###
POST http://localhost:5000/signin  HTTP/1.1
content-type: application/json

{ "_id": 3, "name": "Keith" } 
###

###
DELETE http://localhost:5000/admin/:60723acc0ecac8bd463ffce4           HTTP/1.1
