DELETE http://localhost:3000/clear HTTP/1.1

###
POST http://localhost:3000/signup HTTP/1.1
content-type: application/json

{
    "name": {"sam"},
    "email":{"sam@gmail.com"},
    "password":{"sami"}
}
 
   
###
GET http://localhost:3000

###
POST http://localhost:3000/signin  HTTP/1.1
content-type: application/json

{ "_id": 3, "name": "Keith" } 
###

PATCH http://localhost:3000/schools/1/teacher/2 HTTP/1.1
content-type: application/json

{ "name": "Keith Levi" } 

###
DELETE http://localhost:3000/schools/1/teacher/2 HTTP/1.1

###
POST http://localhost:3000/schools/1/course/2 HTTP/1.1
content-type: application/json

{ "_id": 3, "name": "Fathi" } 
###

PATCH http://localhost:3000/schools/1/courses/2/3 HTTP/1.1
content-type: application/json

{ "name": "Fathi Aswad" } 

###
DELETE http://localhost:3000/schools/1/courses/2/3 HTTP/1.1
